export default [
  {
    "no": 1,
    "client_name": "ABC Company",
    "address": "123 Main Street",
    "phone": "555-1234",
    "type": "website",
    "type_data": "www.abc.com",
    "pic_name": "John Doe",
    "pic_number": "555-5678",
    "status": "active"
  },
  {
    "no": 2,
    "client_name": "XYZ Corporation",
    "address": "456 Elm Street",
    "phone": "555-5678",
    "type": "email",
    "type_data": "info@xyzcorp.com",
    "pic_name": "Jane Smith",
    "pic_number": "555-9876",
    "status": "inactive"
  },
  {
    "no": 3,
    "client_name": "123 Industries",
    "address": "789 Oak Avenue",
    "phone": "555-2468",
    "type": "website",
    "type_data": "www.123industries.com",
    "pic_name": "Michael Johnson",
    "pic_number": "555-4321",
    "status": "active"
  },
  {
    "no": 4,
    "client_name": "ABC Corporation",
    "address": "321 Pine Street",
    "phone": "555-1357",
    "type": "email",
    "type_data": "contact@abccorp.com",
    "pic_name": "Sarah Williams",
    "pic_number": "555-7890",
    "status": "active"
  },
  {
    "no": 5,
    "client_name": "XYZ Enterprises",
    "address": "654 Cedar Avenue",
    "phone": "555-8642",
    "type": "website",
    "type_data": "www.xyzenterprises.com",
    "pic_name": "David Brown",
    "pic_number": "555-0123",
    "status": "inactive"
  },
  {
    "no": 6,
    "client_name": "123 Corporation",
    "address": "987 Elm Street",
    "phone": "555-7392",
    "type": "email",
    "type_data": "info@123corp.com",
    "pic_name": "Jennifer Davis",
    "pic_number": "555-4567",
    "status": "active"
  },
  {
    "no": 7,
    "client_name": "ABC Enterprises",
    "address": "159 Oak Avenue",
    "phone": "555-0284",
    "type": "website",
    "type_data": "www.abcenterprises.com",
    "pic_name": "James Wilson",
    "pic_number": "555-5678",
    "status": "inactive"
  },
  {
    "no": 8,
    "client_name": "XYZ Company",
    "address": "753 Pine Street",
    "phone": "555-8642",
    "type": "email",
    "type_data": "contact@xyzcompany.com",
    "pic_name": "Emily Taylor",
    "pic_number": "555-8901",
    "status": "active"
  },
  {
    "no": 9,
    "client_name": "123 Enterprises",
    "address": "951 Cedar Avenue",
    "phone": "555-7392",
    "type": "website",
    "type_data": "www.123enterprises.com",
    "pic_name": "Matthew Anderson",
    "pic_number": "555-2345",
    "status": "inactive"
  },
  {
    "no": 10,
    "client_name": "ABC Industries",
    "address": "357 Elm Street",
    "phone": "555-2468",
    "type": "email",
    "type_data": "info@abcindustries.com",
    "pic_name": "Olivia Thomas",
    "pic_number": "555-6789",
    "status": "active"
  },
  {
    "no": 11,
    "client_name": "XYZ Corporation",
    "address": "753 Oak Avenue",
    "phone": "555-1357",
    "type": "website",
    "type_data": "www.xyzcorp.com",
    "pic_name": "Daniel Clark",
    "pic_number": "555-8901",
    "status": "active"
  },
  {
    "no": 12,
    "client_name": "123 Company",
    "address": "951 Pine Street",
    "phone": "555-5678",
    "type": "email",
    "type_data": "contact@123company.com",
    "pic_name": "Emma Baker",
    "pic_number": "555-4567",
    "status": "inactive"
  },
  {
    "no": 13,
    "client_name": "ABC Enterprises",
    "address": "357 Cedar Avenue",
    "phone": "555-1234",
    "type": "website",
    "type_data": "www.abcenterprises.com",
    "pic_name": "William Garcia",
    "pic_number": "555-9012",
    "status": "active"
  },
  {
    "no": 14,
    "client_name": "XYZ Industries",
    "address": "753 Elm Street",
    "phone": "555-7392",
    "type": "email",
    "type_data": "info@xyzindustries.com",
    "pic_name": "Sophia Lee",
    "pic_number": "555-3456",
    "status": "active"
  },
  {
    "no": 15,
    "client_name": "123 Corporation",
    "address": "951 Oak Avenue",
    "phone": "555-1357",
    "type": "website",
    "type_data": "www.123corp.com",
    "pic_name": "Jacob Hernandez",
    "pic_number": "555-6789",
    "status": "inactive"
  },
  {
    "no": 16,
    "client_name": "ABC Company",
    "address": "357 Pine Street",
    "phone": "555-5678",
    "type": "email",
    "type_data": "contact@abccompany.com",
    "pic_name": "Isabella Martinez",
    "pic_number": "555-2345",
    "status": "active"
  },
  {
    "no": 17,
    "client_name": "XYZ Corporation",
    "address": "753 Cedar Avenue",
    "phone": "555-1234",
    "type": "website",
    "type_data": "www.xyzcorp.com",
    "pic_name": "Ethan Thompson",
    "pic_number": "555-7890",
    "status": "inactive"
  },
  {
    "no": 18,
    "client_name": "123 Enterprises",
    "address": "951 Elm Street",
    "phone": "555-7392",
    "type": "email",
    "type_data": "info@123enterprises.com",
    "pic_name": "Mia Walker",
    "pic_number": "555-9012",
    "status": "active"
  },
  {
    "no": 19,
    "client_name": "ABC Corporation",
    "address": "357 Oak Avenue",
    "phone": "555-8642",
    "type": "website",
    "type_data": "www.abccorp.com",
    "pic_name": "Liam Hall",
    "pic_number": "555-5678",
    "status": "active"
  },
  {
    "no": 20,
    "client_name": "XYZ Enterprises",
    "address": "753 Pine Street",
    "phone": "555-2468",
    "type": "email",
    "type_data": "contact@xyzenterprises.com",
    "pic_name": "Abigail Scott",
    "pic_number": "555-7890",
    "status": "inactive"
  },
  {
    "no": 21,
    "client_name": "123 Industries",
    "address": "951 Cedar Avenue",
    "phone": "555-1234",
    "type": "website",
    "type_data": "www.123industries.com",
    "pic_name": "Benjamin Allen",
    "pic_number": "555-9012",
    "status": "active"
  },
  {
    "no": 22,
    "client_name": "ABC Enterprises",
    "address": "357 Elm Street",
    "phone": "555-1357",
    "type": "email",
    "type_data": "info@abcenterprises.com",
    "pic_name": "Harper Turner",
    "pic_number": "555-7890",
    "status": "active"
  },
  {
    "no": 23,
    "client_name": "XYZ Company",
    "address": "753 Oak Avenue",
    "phone": "555-5678",
    "type": "website",
    "type_data": "www.xyzcompany.com",
    "pic_name": "Michaela Baker",
    "pic_number": "555-2345",
    "status": "inactive"
  },
  {
    "no": 24,
    "client_name": "123 Enterprises",
    "address": "951 Pine Street",
    "phone": "555-7392",
    "type": "email",
    "type_data": "contact@123enterprises.com",
    "pic_name": "Alexander Wright",
    "pic_number": "555-4567",
    "status": "active"
  },
  {
    "no": 25,
    "client_name": "ABC Industries",
    "address": "357 Cedar Avenue",
    "phone": "555-1234",
    "type": "website",
    "type_data": "www.abcindustries.com",
    "pic_name": "Ava Wilson",
    "pic_number": "555-9012",
    "status": "inactive"
  }
]